- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: go
  ansible.builtin.import_role:
    name: common
    tasks_from: go

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup    

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd    

        

