- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployement
  ansible.builtin.service:
    path: "/app"   #if we keep /app it will remove total directory
    state: absent   
    force: yes