- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: node js
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: cart setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd    

        

